### ISSUE TITLE
Plans to support encoder API?

### ISSUE THREAD

**Issue by blakehawkins** [henkelmax/opus4j#4]
Hi! Thank you for open sourcing this, it works great

The encoder API supports a bunch of useful stuff like VBR, sample rate, inband FEC, and so on

Do you plan to expand on the rust bindings for the rest of https://docs.rs/opus/latest/opus/struct.Encoder.html ?

**Comment by henkelmax** [comment]
This was designed to only include the features needed for https://github.com/henkelmax/simple-voice-chat
There are no plans on adding anything else.
